@startuml informasjonemodell-enkel

hide empty members
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

class Diagnose <<Condition>> [[StructureDefinition-lmdi-condition.html Diagnose _blank]]
class Episode <<Encounter>> [[StructureDefinition-lmdi-encounter.html Episode _blank]]
class Helsepersonell <<Practitioner>> [[StructureDefinition-lmdi-practitioner.html Helsepersonell _blank]]
class Legemiddel <<Medication>> [[StructureDefinition-lmdi-medication.html Legemiddel _blank]]
class Legemiddeladministrering <<MedicationAdministration>> [[StructureDefinition-lmdi-medicationadministration.html Legemiddeladministrering _blank]]
class Legemiddelrekvirering <<MedicationRequest>> [[StructureDefinition-lmdi-medicationrequest.html Legemiddelrekvirering _blank]]
class Organisasjon <<Organization>> [[StructureDefinition-lmdi-organization.html Organisasjon _blank]]
class Pasient <<Patient>> [[StructureDefinition-lmdi-patient.html Pasient _blank]]
class Virkestoff <<Substance>> [[StructureDefinition-lmdi-substance.html Virkestoff _blank]]

Diagnose --> Pasient : "1..1\nsubject"
Episode --> Organisasjon : "0..1\nserviceProvider"
Legemiddel --> Virkestoff : "0..*\ningredient.itemReference"
Legemiddel --> Legemiddel : "0..*\ningredient.itemReference"
Legemiddeladministrering --> Legemiddel : "1..1\nmedicationReference"
Legemiddeladministrering --> Pasient : "1..1\nsubject"
Legemiddeladministrering --> Episode : "0..1\ncontext"
Legemiddeladministrering --> Diagnose : "0..*\nreasonReference"
Legemiddeladministrering --> Legemiddelrekvirering : "0..1\nrequest"
Legemiddelrekvirering --> Legemiddel : "1..1\nmedicationReference"
Legemiddelrekvirering --> Pasient : "1..1\nsubject"
Legemiddelrekvirering --> Episode : "0..1\nencounter"
Legemiddelrekvirering --> Helsepersonell : "0..1\nrequester"
Legemiddelrekvirering --> Diagnose : "0..*\nreasonReference"
Legemiddelrekvirering --> Legemiddelrekvirering : "0..1\npriorPrescription"
Organisasjon --> Organisasjon : "0..1\npartOf"

@enduml